name: dart_ansi
description: Ansi support for Dart.
version: 1.0.0
repository: https://github.com/dorireuv/dart_ansi
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  dart_guava:
    git:
      url: https://github.com/dorireuv/dart_guava.git
      ref: main

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
